### ISSUE TITLE
Possible to add a Large Fonts like confluence had?

### ISSUE THREAD

**Issue by dantheother** [linknetx/skin.estuary-plus#1]
Loving what you have done to estuary, which is a really neat skin, just dang impossible to read when I'm tired on my phone!

I know diddly about skinning kodi, but what would be involved in adding a Large Fonts option like the old Confluence skin had? Happy to mess around with a copy if it is feasible (and with some guidance).

Cheers!

**Comment by linknetx** [comment]
You're using it on your phone ? You probably need a magnifying glass !!!

Seriously though, it's not just a matter of increasing the font size, a great many of the screen elements need repositioning to cater for the larger fonts. So I'm afraid it's a lot of work and something I just don't have the time for.

Best Regards

**Comment by dantheother** [comment]
Ahh, no worries., I feared it wouldn't just be "edit this xml boom done". I'll invest in a magnifying glass then 😀 

Thanks for the reply!
